### ISSUE TITLE
Hide notification instead of killing the process

### ISSUE THREAD

**Issue by IAM-marco** [ibhagwan/lemontify#1]
Hello!
I'm the author of [this](https://www.reddit.com/r/unixporn/comments/6gzxgf/lemonbar_my_custom_volume_level_indicator/)

I have been been looking at the code and have noticed that you're killing `lemonbar` process whenever you display a new notification.

In my original implementation, lemonbar was crashing my compositing manager. So, the "workaround" I found was to use `xdotool` to hide the notification instead of killing it.

For example:

    for wid in $(xdotool search --classname lemonbar); do
        xdotool windowunmap $wid
    done

**EDIT** Consider using `exec -a "some_name" lemonbar <opts>'`. In this way, the process that launches the notification is renamed to "some_name" and you can safely hide only that specific notification (volume, brightness, whatever) instead of all notifications and bars using lemonbar.

**Comment by ibhagwan** [comment]
Thanks for the elegant solution: [committed to the code](https://github.com/ibhagwan/lemontify/commit/713864fc109da8ce7b5e1e8c8443d54af87272b4)
