### ISSUE TITLE
Lemonbar parameters are parsed incorrectly

### ISSUE THREAD

**Issue by IAM-marco** [ibhagwan/lemontify#2]
This is a very strange bug.

I am on i3wm and when I tried to run your script, I wasn't getting a floating window, even if I set lemonbar to be floating in my i3wm config. I double checked to see if you were using `-d` option, and indeed you are (notice how the bar is stacked below my polybar and above my terminal).

![2020-03-22-185853_560x415_scrot](https://user-images.githubusercontent.com/8115374/77256521-37b50000-6c6f-11ea-8ea7-f2417af84f36.png)

Then I tried to fiddle with `baropt="-d -g ${barw}x${barh}+${barx}+${bary}"` option and I moved `-d` after the geometry option. The bar was now sort of floating, but the position was totally wrong.

![2020-03-22-185717_1919x215_scrot](https://user-images.githubusercontent.com/8115374/77256575-7480f700-6c6f-11ea-864d-6db9aebf17b9.png)

Also, fun fact: to take these screenshots I used `-p` lemonbar option so that the process doesn't exits until you manually kill it. I have found out that if I set `baropt="-p -g ${barw}x${barh}+${barx}+${bary} -d"` the notification is sized correctly and I believe it is also position correctly. However, the `-p` option is ignored, so the notification disappears after `$duration` seconds.

Any idea on how to fix this?

**Comment by ibhagwan** [comment]
You're correct, when I added the `-m` flag I incorrectly added it to the `getopt` line as an argument that requires additional variable, [fixed in this commit](https://github.com/ibhagwan/bar/commit/d5d2df4ff9244d8a349064ccb77c53db846e5ce2)
